//定义分享的平台
enum SHARE_MEDIA {
  GOOGLEPLUS,
  GENERIC,
  SMS,
  EMAIL,
  SINA,
  QZONE,
  QQ,
  RENREN,
  WEIXIN,
  WEIXIN_CIRCLE,
  WEIXIN_FAVORITE,
  TENCENT,
  DOUBAN,
  FACEBOOK,
  FACEBOOK_MESSAGER,
  TWITTER,
  LAIWANG,
  LAIWANG_DYNAMIC,
  YIXIN,
  YIXIN_CIRCLE,
  INSTAGRAM,
  PINTEREST,
  EVERNOTE,
  POCKET,
  LINKEDIN,
  FOURSQUARE,
  YNOTE,
  WHATSAPP,
  LINE,
  FLICKR,
  TUMBLR,
  ALIPAY,
  KAKAO,
  DROPBOX,
  VKONTAKTE,
  DINGTALK,
  MORE
}

//定义分享的类型
enum ShareType {
  SHARE_TYPE_TEXT, //分享纯文本
  SHARE_TYPE_IMAGE_LOCAL, //分享纯图片本地
  SHARE_TYPE_IMAGE_URL, //纯图片http
  SHARE_TYPE_IMAGE_AND_TEXT, //图文
  SHARE_TYPE_MUSIC, //分享音乐
  SHARE_TYPE_VIDEO, //分享视频
  SHARE_TYPE_WEB, //分享web
  SHARE_TYPE_EMOJI, //微信表情
  SHARE_TYPE_FILE, //文件
  SHARE_TYPE_MIN_APP //小程序（测试）
}
